name: Android Publish Play Store

env:
    # The name of the main module repository
    main_project_module: Namiokai

    # The name of the Play Store
    playstore_name: Namiokai

on:
    push:
        branches:
            - 'release/**'

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Set Up JDK
              uses: actions/setup-java@v3
              with:
                  java-version: 17

            - name: Change wrapper permissions
              run: chmod +x ./gradlew

            - name: Create Google Services JSON File
              env:
                  GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
              run: echo $GOOGLE_SERVICES_JSON | base64 -di > ./Namiokai/src/release/google-services.json

            - name: Run Tests
              run: ./gradlew test

            - name: Build Project
              run: ./gradlew build

            - name: Build Release AAB
              run: ./gradlew bundleRelease

            - name: Sign AAB
              uses: r0adkll/sign-android-release@v1
              with:
                  releaseDirectory: app/build/outputs/bundle/release
                  signingKeyBase64: ${{ secrets.SIGN_KEY }}
                  alias: ${{ secrets.ALIAS }}
                  keyStorePassword: ${{ secrets.STORE_KEY_PASSWORD }}
                  keyPassword: ${{ secrets.KEY_PASSWORD }}

            - name: Deploy to Play Store
              uses: r0adkll/upload-google-play@v1
              with:
                  serviceAccountJsonPlainText: ${{secrets.SERVICE_ACCOUNT}}
                  packageName: com.namiokai
                  releaseFiles: app/build/outputs/bundle/release/app-release.aab
                  track: internal
                  status: draft