name: Android Publish Play Store

env:
  main_project_module: app
  playstore_name: Namiokai

on:
  push:
    branches:
      - 'release/**'

  workflow_dispatch:

jobs:
  release-build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Create Keystore files
        env:
          SIGN_KEY: ${{ secrets.SIGN_KEY }}
          SIGN_KEY_DEBUG: ${{ secrets.SIGN_KEY_DEBUG }}
        run: |
          echo $SIGN_KEY | base64 -di > ./namiokai-release.jks
          echo $SIGN_KEY_DEBUG | base64 -di > ./namiokai-debug.jks
      - name: Create Google Services JSON File
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          GOOGLE_SERVICES_JSON_DEBUG: ${{ secrets.GOOGLE_SERVICES_JSON_DEBUG }}
        run: |
          mkdir -p ./app/src/release
          mkdir -p ./app/src/debug
          echo $GOOGLE_SERVICES_JSON | base64 -di > ./app/src/release/google-services.json
          echo $GOOGLE_SERVICES_JSON_DEBUG | base64 -di > ./app/src/debug/google-services.json

      - name: Build Project
        run: ./gradlew build

      - name: Build Release AAB
        run: ./gradlew bundleRelease

      - name: Deploy to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{secrets.SERVICE_ACCOUNT}}
          packageName: com.namiokai
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          whatsNewDirectory: distribution/whatsnew
          track: internal
          status: completed
